### ISSUE TITLE
Route Cache Caches the underlying API calls as well!

### ISSUE THREAD

**Issue by sathishzakapps** [dulnan/nuxt-multi-cache#64] opened 2024-07-29 13:30 UTC
Hi @dulnan 

I'm encountering an issue with version 3.3.0.

When using the Route Cache for the route ~/pages/product/[id].vue, it caches the underlying API calls as well. When rendering the page, I use two API calls: one to get content (/api/cms/product) and the actual product data (/api/productInfo?id=productId), using Redis as the cache base.

<img width="419" alt="image" src="https://github.com/user-attachments/assets/dae4b52f-869d-4a15-a2af-7a50736059ca">

I can see three entries in the cache: one for the actual page and two for /api/cms/product and /api/productInfo.

I would like only the page to be cached. Is there any way to achieve this? It worked as expected in version 3.2.0.

Thanks in advance; any help would be greatly appreciated.

**Comment by dulnan** [comment] 2024-07-29 13:41
That sounds very weird and unexpected. I will look into this now.

**Comment by sathishzakapps** [comment] 2024-07-29 13:58
Thank you @dulnan 

To add to the above I have tried to avoid caching the api calls using the enabledForRequest but does not helped.

<img width="499" alt="image" src="https://github.com/user-attachments/assets/2b39ab7a-4390-4d73-bf8b-3fd18a9530cd">

**Comment by dulnan** [comment] 2024-07-29 14:05
I am unable to reproduce this behaviour. I have created a new API route that does not call useRouteCache() at all, meaning it should not be cached. I then call this API using useFetch() on a page that calls useRouteCache() with isCacheable(). I only have one entry in the route cache, the page. Only when I explicitly call isCacheable() inside the API event handler do I see that its response has been cached.

If you say that`enabledForRequest` does not work, then something super fishy must be going on: This method is called very early on in the request life cycle and if its returns false, then the cache is completely unavailable for any subsequent code... This makes no sense :thinking: 

Do you have other places where you use useRouteCache()? e.g. inside a server middleware?

**Comment by dulnan** [comment] 2024-07-29 14:09
Okay just as I sent it, I was able to reproduce it. And... it's **VERY** weird what I'm seeing. This is impossible.

**Comment by dulnan** [comment] 2024-07-29 14:22
Yeah, I found the problem, look:

**Page component**
```vue
<script lang="ts" setup>
import { useFetch, useRequestEvent } from '#imports'

const event = useRequestEvent()

if (event) {
  event.context.foobar = 'TEST'
}

const { data } = await useFetch('/api/uncacheableApi')
</script>
```

**API route**
```typescript
import { defineEventHandler } from 'h3'

export default defineEventHandler<{ data: number }>((event) => {
  console.log('Test: ' + event.context.foobar)
  return {
    data: Date.now(),
  }
})
```

This logs `Test: TEST` to the console. Apparently the context is shared (?!) for the entire request, *including* any API calls that are made during server side rendering. One of the things I did change in the latest release was using this exact `event.context` to add the cache helper, instead of putting it on the `event` directly. This explains why `enabledForRequest` does not work: The first time it's called, your method returns `true`, because that path is not starting with `/api`. But at that point it is now set in `event.context` and thus available for any and all API routes. Crazy.

I will do a fix now and release it asap.

**Comment by sathishzakapps** [comment] 2024-07-29 14:29
Thank you so much @dulnan. Understood whats happening :)

**Comment by dulnan** [comment] 2024-07-29 15:09
I have just released 3.3.1, would you like to give it a try?

Also thank you very much for bringing this issue to my attention! I would probably not have noticed this for some time and seeing as this bug could result in very unexpected runtime behaviour, I'm glad I was able to fix it now.

**Comment by sathishzakapps** [comment] 2024-07-29 15:30
@dulnan Thank you so much!!! that worked :) the quickest response I have ever got! 

you are doing great help by writing this module, we understand how important the cache is, providing the Nuxt's performance. 

However, I encountered the below error. while serving the cached response.

````
Serving cached route for path: /product/A-23958 {
  fullKey: '/product/A-23958'
}

[nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client
  at new NodeError (node:internal/errors:405:5)  
  at ServerResponse.setHeader (node:_http_outgoing:652:11)  
  at setResponseHeaders (./.output/server/chunks/runtime.mjs:2559:20)  
  at Object.handler (./.output/server/chunks/runtime.mjs:5423:7)  
  at ./.output/server/chunks/runtime.mjs:3063:31  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.callAsync (./.output/server/chunks/runtime.mjs:5544:16)  
  at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3329:7)
````

Kindly let me know if I can avoid this error?

**Comment by dulnan** [comment] 2024-07-29 15:35
Sure, could you show me which other modules you have installed or nitro/h3 related libraries you use? I know for example that the `h3-compression` library is not compatible with this module due to the way the response is compressed.

**Comment by sathishzakapps** [comment] 2024-07-29 15:49
Surely, 
<img width="441" alt="image" src="https://github.com/user-attachments/assets/2863bbda-7dc0-4d94-b8ea-af34ccc925ed">

and nitro config

<img width="650" alt="image" src="https://github.com/user-attachments/assets/f0660ab7-5911-4c5d-86b5-03594d36ffbd">

**Comment by dulnan** [comment] 2024-07-30 04:25
Could you try (if easily possible) to disable nuxt-security to see if it would resolve the issue?

**Comment by sathishzakapps** [comment] 2024-07-30 06:29
@dulnan tried to removing them but no luck. not sure whats happening, shall check if any of the code that we wrote causing this issue and come back here. If I need further help..

**Comment by sathishzakapps** [comment] 2024-07-30 09:05
@dulnan while serving the cache in serveCacheRoute, we set the headers using setResponseHeaders as well as we are iterating headers and set the headers using response.headers.set!

Not sure which is causing the issue, just thought of sharing it here!

<img width="564" alt="image" src="https://github.com/user-attachments/assets/ff8f70f0-a4b6-47db-a021-567bb96dde10">

**Comment by dulnan** [comment] 2024-07-31 03:59
Oh I see. I did not think of this scenario. Generally I would advise against using route cache + route rules together, but in this case it would be a valid use case to add headers. I will check to see if it's possible.

**Comment by sathishzakapps** [comment] 2024-07-31 07:16
Thanks @dulnan

**Comment by dulnan** [comment] 2024-08-01 06:18
I looked into it and once again it's such an annoying problem with the way h3/nitro are setup. For some context: As an author of a module like nuxt-multi-cache, it's very hard to implement route caching. There are only so many ways one can hook into the life cycle of the request. The problem now is that the part where I cache the response happens at the very end of the request. This is why the module is able to also cache the headers applied by your route rule *initially* and also stores them in the cache. However, in the second request, when the module wants to serve something from cache, the only "sane" way to achieve that is inside the `onRequest` hook. There I load it from cache and immediately return the response. However: Nitro will still go through the entire rest of the request, calling hooks, applying route rules, etc. As of now I have not found a way to prevent that reliably.

That was also the case pre 3.3.0, however there it worked because "serving from cache" was implemented as an "event handler", because nitro did not provide a hook at that time. But in order to implement "stale if error" and "stale while revalidate", I could no longer implement it as an event handler.

Anyway, as a temporary workaround, I suggest to not use routeRules to apply headers but instead apply them in a server middleware using `setResponseHeader`. In the meantime I will continue to explore options to make route rules work with route cache.

**Comment by sathishzakapps** [comment] 2024-08-01 08:40
Thank you for the detailed explanation @dulnan. For now I shall write the no-cache to the routes that I am not caching at all and I'll see if I need them in the routes I am caching and add them as necessary...

I need to understand more on h3/nitro implementation.

Thank you once again for the prompt replies :) helped me a lot..

**Comment by dulnan** [comment] 2024-08-01 08:43
I may have found a workaround which I've already implemented in #66, but I still need to do some more testing. You may not need to apply the workaround for long, if it turns out to work properly!

**Comment by sathishzakapps** [comment] 2024-08-01 08:51
Great to hear! Hope all will be good (y) in the new PR and works well!!

**Comment by dulnan** [comment] 2024-08-25 07:30
@sathishzakapps I just merged the change that should hopefully fix this issue. I will do some more testing (together with other fixes pushed today) and if all works, create a new release today.

**Comment by sathishzakapps** [comment] 2024-08-26 12:24
@dulnan Thank you for the update, I shall get the latest and test them and let you know in case of any issues? Once again thank you!!!

**Closed** 2024-11-15 07:46 UTC
