### ISSUE TITLE
No redis connection with DataCache

### ISSUE THREAD

**Issue by harley5303** [dulnan/nuxt-multi-cache#10] opened 2023-03-21 11:26 UTC
Hi,

i make some tests with your module and can´t understand the reason why ist does not work.
In nuxt.config.js:
```
multiCache: {
        data: {
            enabled: true,
            storage: {
                driver: redisDriver({
                    base: "",
                    host: '127.0.0.1',
                    port: 6379,
                    //password: 'REDIS_PASSWORD'
                })
            }
        }
    },
```
On my serverside endpoint /api/test
`import { useDataCache } from '#nuxt-multi-cache/composables';`
```    
const { value, addToCache } = await useDataCache('my_data')
    if (value) {
        return value
    }
    const response = await getLiveData()
    addToCache(response)
```

This has no effect. Nuxt dont connect to the Redis-Server.

A second test with unstoreage works...
```
import { createStorage } from "unstorage";
import redisDriver from "unstorage/drivers/redis";
```
```
const storage = createStorage({
        driver: redisDriver({
            base: "",
            host: '127.0.0.1',
            port: 6379,
            //password: 'REDIS_PASSWORD'
        }),
    });

    const item = await storage.getItem("my_data");
    if(item){
        return item
    }
```

I check your documentation but i can not see the problem.
Have you any idea how to solve the problem?

SETUP: nuxt 3.2.2; nodejs 18; redis 6.0.9 via Mamp pro on Macbook pro m1

**Comment by dulnan** [comment] 2023-03-21 11:59
Interesting. I think I know what the problem is and will try to recreate it locally. I‘ll get back to you once I know more.

**Comment by dulnan** [comment] 2023-04-06 11:12
I think this is related to something I have fixed in a beta release. The way that storage drivers can be configured has changed. Could you install the 3.0.0 beta release and give it a try?

```
npm install nuxt-multi-cache@3.0.0-beta0 --save
```

And here's the documentation for the changes introduced:

https://deploy-preview-12--nuxt-multi-cache.netlify.app/overview/server-options

**Closed** 2023-08-13 15:25 UTC
