### ISSUE TITLE
Problem using Vue alias

### ISSUE THREAD

**Issue by sergeev-vn** [dulnan/nuxt-multi-cache#27] opened 2023-09-12 08:14 UTC
I'm using [vue3-runtime-template](https://www.npmjs.com/package/vue3-runtime-template) and according to the documentation I must use the with-compiler Vue.js version:

``` js
// nuxt.config.js
{
 (...)

 hooks: {
      'vite:extendConfig': (config, { isClient, isServer }) => {
        if (isClient) {
          config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
        }
      },
    },

  (...)
```
But when using along with nuxt-multi-cache an error occurs:
`[14:52:35]  ERROR  Failed to load url vue/dist/vue.esm-bundler/server-renderer (resolved id: vue/dist/vue.esm-bundler/server-renderer) in /home/project/frontend/node_modules/nuxt-multi-cache/dist/runtime/components/RenderCacheable/helpers/index.mjs. Does the file exist?
`

Is it possible to solve this somehow? 

@dulnan

**Comment by dulnan** [comment] 2023-10-01 15:11
Setting an alias for `vue` and making it point to a specific file in a folder will break all imports that start with `vue/`.

The `vue` package has quite a few exports:

https://github.com/vuejs/core/blob/main/packages/vue/package.json#L34

The problem here is that the `RenderCacheable` component (correctly) imports a function from `vue/server-renderer`. But because an alias for `vue` was added it now tries to import it from `vue/dist/vue.esm-bundler/server-renderer`.

I was able to reproduce the issue and fix it by creating an additional alias:

```typescript
'vite:extendConfig': (config, { isClient, isServer }) => {
  config.resolve.alias['vue/server-renderer'] = 'vue/server-renderer'
  config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
},
```

Keep in mind that while this specific export is now fixed 9 other exports from `vue` remain broken. You would have to create an alias for all the exports that are defined in the vue package.json.

**Closed by dulnan** 2023-10-01 15:11 UTC
